# FEATURE-02 (Palveluun kirjautuminen)  


| | |
|:-:|:-:|
| Ominaisuus ID | FEATURE-02 |
| Osajärjestelmä, mihin ominaisuus liittyy | Portfoliosovellus |
| Ominaisuuden vastuuhenkilö | Nina |
| Status | In progress |  


### Kuvaus   

### Toteutus  
> tekstiä
### Ominaisuuteen liittyvät rajaukset, vaatimukset, käyttötapaukset  
> tekstiä
### Alustavat käyttäjätarinat (User storys)  
> tekstiä
### Käyttöliittymänäkymä Mockup  
> tekstiä
### Testaus/ mahdolliset hyväksyntäkriteerit
> tekstiä
